export { default as Header } from './header/Header';
export { default as About } from './about/About';
export { default as Footer } from './footer/Footer';
export { default as Navbar } from './navbar/Navbar';
export { default as Services } from './services/Services';
export { default as Login } from './register/Login';
export { default as Signup } from './register/Signup';
export { default as Musics } from './music/Musics';
export { default as NotFound } from './error/NotFound';
